"""
ATS analysis using Google Gemini.
Returns a structured dict with scores, keywords, and suggestions.
"""
import json
import os
import re

from google import genai


def _get_client():
    api_key = os.environ.get("GEMINI_API_KEY", "")
    if not api_key:
        raise EnvironmentError(
            "GEMINI_API_KEY is not set. Add it to your .env file or Streamlit secrets."
        )
    return genai.Client(api_key=api_key)


ANALYSIS_PROMPT = """
You are an expert ATS (Applicant Tracking System) resume analyzer.

Analyze the following resume against the provided job description for the role of "{job_role}".

Return ONLY a valid JSON object (no markdown, no explanation) with this exact structure:
{{
  "overall_score": <integer 0-100>,
  "section_scores": {{
    "keywords_match": <integer 0-100>,
    "skills_alignment": <integer 0-100>,
    "experience_match": <integer 0-100>,
    "education_match": <integer 0-100>,
    "format_structure": <integer 0-100>
  }},
  "matched_keywords": [<list of strings>],
  "missing_keywords": [<list of strings>],
  "strengths": [<list of 3-5 strength strings>],
  "improvements": [<list of 5-8 specific, actionable improvement strings>],
  "summary": "<2-3 sentence executive summary of the match>"
}}

---
JOB ROLE: {job_role}

JOB DESCRIPTION:
{job_description}

---
RESUME:
{resume_text}
"""


def analyze_resume(job_role: str, job_description: str, resume_text: str) -> dict:
    """
    Call Gemini to analyze a resume against a job description.
    Returns a parsed dict with all ATS metrics.
    """
    client = _get_client()

    prompt = ANALYSIS_PROMPT.format(
        job_role=job_role,
        job_description=job_description,
        resume_text=resume_text,
    )

    # Try models in order — use what's actually available for this API key
    # (gemini-1.5-* is NOT available; confirmed via client.models.list())
    models_to_try = [
        "gemini-2.0-flash-lite",   # lightest, best for free quota
        "gemini-2.0-flash",        # standard fallback
        "gemini-2.5-flash",        # more capable fallback
    ]

    last_error = None
    for model_name in models_to_try:
        try:
            response = client.models.generate_content(
                model=model_name,
                contents=prompt,
            )
            raw = response.text.strip()
            break
        except Exception as e:
            last_error = e
            if "429" in str(e) or "RESOURCE_EXHAUSTED" in str(e):
                continue   # try next model
            raise          # non-quota error → surface immediately
    else:
        raise RuntimeError(
            f"All Gemini models are rate-limited. Please wait a minute and try again.\n"
            f"Last error: {last_error}"
        )

    # Strip markdown code fences if Gemini wraps the JSON
    raw = re.sub(r"^```(?:json)?\s*", "", raw)
    raw = re.sub(r"\s*```$", "", raw)

    try:
        result = json.loads(raw)
    except json.JSONDecodeError as e:
        raise ValueError(
            f"Gemini returned invalid JSON:\n{raw}\n\nError: {e}"
        ) from e

    # Validate required keys
    required_keys = [
        "overall_score",
        "section_scores",
        "matched_keywords",
        "missing_keywords",
        "strengths",
        "improvements",
        "summary",
    ]
    for key in required_keys:
        if key not in result:
            raise ValueError(f"Missing key in Gemini response: {key}")

    return result


def generate_text_report(
    job_role: str, job_description: str, resume_text: str, analysis: dict
) -> str:
    """Generate a plain-text downloadable report."""
    lines = [
        "=" * 60,
        "ATS RESUME ANALYSIS REPORT",
        "=" * 60,
        f"Job Role: {job_role}",
        f"Overall ATS Score: {analysis['overall_score']}/100",
        "",
        "SECTION SCORES",
        "-" * 40,
    ]
    for section, score in analysis["section_scores"].items():
        label = section.replace("_", " ").title()
        lines.append(f"  {label}: {score}/100")

    lines += [
        "",
        "EXECUTIVE SUMMARY",
        "-" * 40,
        analysis.get("summary", ""),
        "",
        "STRENGTHS",
        "-" * 40,
    ]
    for i, s in enumerate(analysis.get("strengths", []), 1):
        lines.append(f"  {i}. {s}")

    lines += [
        "",
        "MATCHED KEYWORDS",
        "-" * 40,
        ", ".join(analysis.get("matched_keywords", [])),
        "",
        "MISSING KEYWORDS",
        "-" * 40,
        ", ".join(analysis.get("missing_keywords", [])),
        "",
        "IMPROVEMENT SUGGESTIONS",
        "-" * 40,
    ]
    for i, tip in enumerate(analysis.get("improvements", []), 1):
        lines.append(f"  {i}. {tip}")

    lines += ["", "=" * 60, "Generated by ATS Resume Checker", "=" * 60]
    return "\n".join(lines)


def generate_pdf_report(job_role: str, analysis: dict) -> bytes:
    """
    Generate a professionally styled PDF report using reportlab.
    Returns raw PDF bytes suitable for st.download_button.
    """
    import io
    import re
    import html as html_mod
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    )
    from reportlab.graphics.shapes import Drawing, Circle, String, Wedge, Rect

    # ── Sanitise text coming from Gemini (may contain HTML tags / markdown) ───
    def clean(text: str) -> str:
        text = html_mod.unescape(str(text))           # &amp; → &
        text = re.sub(r"<[^>]+>", "", text)           # strip <a href=…> etc.
        text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)  # [t](url) → t
        text = re.sub(r"\*{1,2}([^*]+)\*{1,2}", r"\1", text)  # **bold** → bold
        text = re.sub(r"_{1,2}([^_]+)_{1,2}", r"\1", text)    # __x__ → x
        text = re.sub(r"`([^`]+)`", r"\1", text)               # `code` → code
        return text.strip()

    # ── Colour palette ────────────────────────────────────────────────────────
    CARD       = colors.HexColor("#1a1f2e")
    ACCENT     = colors.HexColor("#6c63ff")
    GREEN      = colors.HexColor("#10b981")
    RED        = colors.HexColor("#ef4444")
    TEXT_LIGHT = colors.HexColor("#e2e8f0")
    TEXT_MUTED = colors.HexColor("#94a3b8")
    WHITE      = colors.white
    TEXT_DARK  = colors.HexColor("#1e293b")
    TEXT_MUTED_DARK = colors.HexColor("#475569")

    W, H = A4
    buf  = io.BytesIO()

    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18*mm, rightMargin=18*mm,
        topMargin=8*mm,  bottomMargin=12*mm,
    )

    styles = getSampleStyleSheet()

    def sty(name, **kw):
        return ParagraphStyle(name, parent=styles["Normal"], **kw)

    S_TITLE   = sty("ptitle",   fontSize=20, textColor=WHITE,      leading=26, spaceAfter=2)
    S_SUBHEAD = sty("psubhead", fontSize=10, textColor=TEXT_MUTED, leading=14, spaceAfter=4)
    S_BODY_LIGHT = sty("pbody_light", fontSize=9, textColor=TEXT_LIGHT, leading=13, spaceAfter=3)

    S_SECTION = sty("psection", fontSize=8,  textColor=TEXT_MUTED_DARK, leading=11,
                    spaceAfter=4, spaceBefore=8,
                    fontName="Helvetica-Bold", letterSpacing=1.0, textTransform="uppercase")
    S_BODY    = sty("pbody",    fontSize=9,  textColor=TEXT_DARK, leading=13, spaceAfter=3)
    S_BULLET  = sty("pbullet",  fontSize=9,  textColor=TEXT_DARK, leading=13,
                    spaceAfter=3, leftIndent=12, firstLineIndent=-12)

    overall   = analysis["overall_score"]

    def score_hex(s):
        if s >= 75: return "#10b981"
        if s >= 50: return "#f59e0b"
        return "#ef4444"

    # ── Page handlers ─────────────────────────────────────────────────────────
    def first_page(canvas, doc):
        """Dark card banner only on page 1."""
        canvas.saveState()
        canvas.setFillColor(CARD)
        canvas.roundRect(13*mm, H - 40*mm, W - 26*mm, 32*mm, 8, fill=1, stroke=0)
        canvas.setFillColor(ACCENT)
        canvas.roundRect(13*mm, H - 40*mm, 5, 32*mm, 2, fill=1, stroke=0)
        canvas.restoreState()

    def later_page(canvas, doc):
        """Plain white background + subtle footer on subsequent pages."""
        canvas.saveState()
        canvas.setFillColor(TEXT_MUTED_DARK)
        canvas.setFont("Helvetica", 7)
        canvas.drawCentredString(W / 2, 10*mm,
            f"ATS Resume Checker  ·  {job_role}  ·  Page {doc.page}")
        canvas.restoreState()

    story = []

    # ── Score ring ────────────────────────────────────────────────────────────
    RS = 100
    d  = Drawing(RS, RS)
    cx = cy = RS / 2
    r_out, r_in = 46, 34
    d.add(Circle(cx, cy, r_out, fillColor=colors.HexColor("#1e293b"), strokeColor=None))

    arc_deg = overall * 3.6
    steps   = max(1, int(arc_deg / 4))
    s_col   = colors.HexColor(score_hex(overall))
    for i in range(steps):
        a0 = 90 - (i + 1) * (arc_deg / steps)
        d.add(Wedge(cx, cy, r_out, a0, a0 + arc_deg / steps + 0.4,
                    fillColor=s_col, strokeColor=None))
    d.add(Circle(cx, cy, r_in, fillColor=CARD, strokeColor=None))
    d.add(String(cx, cy + 4,  str(overall),
                 fontSize=20, fontName="Helvetica-Bold",
                 fillColor=s_col, textAnchor="middle"))
    d.add(String(cx, cy - 8,  "/100",
                 fontSize=6, fontName="Helvetica",
                 fillColor=colors.HexColor("#64748b"), textAnchor="middle"))
    lbl = ("Excellent" if overall >= 85 else "Good" if overall >= 70
           else "Fair" if overall >= 50 else "Needs Work")
    d.add(String(cx, cy - 19, lbl,
                 fontSize=7, fontName="Helvetica-Bold",
                 fillColor=s_col, textAnchor="middle"))

    # ── Header table: ring | title ────────────────────────────────────────────
    title_block = [
        Paragraph("ATS Resume Analysis Report", S_TITLE),
        Paragraph(f"Role: <b>{clean(job_role)}</b>", S_SUBHEAD),
        Paragraph(
            f"Overall ATS Score: "
            f"<font color='{score_hex(overall)}'><b>{overall}/100</b></font>",
            S_BODY_LIGHT,
        ),
    ]
    hdr = Table([[d, title_block]], colWidths=[RS + 8, None])
    hdr.setStyle(TableStyle([
        ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING",  (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("BACKGROUND",   (0, 0), (-1, -1), CARD),
    ]))
    story.append(hdr)
    story.append(Spacer(1, 5*mm))

    # ── Executive summary ─────────────────────────────────────────────────────
    summary = clean(analysis.get("summary", ""))
    if summary:
        story.append(Paragraph("Executive Summary", S_SECTION))
        story.append(Paragraph(summary, S_BODY))
        story.append(HRFlowable(width="100%", thickness=0.5,
                                color=colors.HexColor("#1e293b"), spaceAfter=2))

    # ── Section scores ────────────────────────────────────────────────────────
    story.append(Paragraph("Section Scores", S_SECTION))
    BAR_COLORS = {
        "keywords_match":   "#6c63ff",
        "skills_alignment": "#10b981",
        "experience_match": "#f59e0b",
        "education_match":  "#3b82f6",
        "format_structure": "#ec4899",
    }
    LABELS = {
        "keywords_match":   "Keywords Match",
        "skills_alignment": "Skills Alignment",
        "experience_match": "Experience Match",
        "education_match":  "Education Match",
        "format_structure": "Format & Structure",
    }
    BAR_W   = 110 * mm
    bar_rows = []
    for key, lbl in LABELS.items():
        sc      = analysis["section_scores"].get(key, 0)
        bar_col = colors.HexColor(BAR_COLORS[key])
        bd      = Drawing(BAR_W, 12)
        bd.add(Rect(0, 3, BAR_W, 5,
                    fillColor=colors.HexColor("#e2e8f0"), strokeColor=None, rx=2, ry=2))
        fw = BAR_W * sc / 100
        if fw > 0:
            bd.add(Rect(0, 3, fw, 5, fillColor=bar_col, strokeColor=None, rx=2, ry=2))
        bar_rows.append([
            Paragraph(lbl, sty(f"bl{key}", fontSize=8, textColor=TEXT_DARK, leading=11)),
            bd,
            Paragraph(
                f"<font color='{BAR_COLORS[key]}'><b>{sc}%</b></font>",
                sty(f"bp{key}", fontSize=8, textColor=TEXT_DARK, leading=11),
            ),
        ])
    bar_tbl = Table(bar_rows, colWidths=[48*mm, BAR_W, 14*mm])
    bar_tbl.setStyle(TableStyle([
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING",   (0, 0), (-1, -1), 2),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 2),
        ("TOPPADDING",    (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ]))
    story.append(bar_tbl)
    story.append(Spacer(1, 3*mm))

    # ── Keywords ──────────────────────────────────────────────────────────────
    matched = analysis.get("matched_keywords", [])
    missing = analysis.get("missing_keywords", [])
    kw_data = [
        [Paragraph(f"✅ Matched  ({len(matched)})", sty("k_h", fontSize=8, textColor=TEXT_MUTED, fontName="Helvetica-Bold", spaceAfter=4)),
         Paragraph(f"❌ Missing  ({len(missing)})",  sty("k_i", fontSize=8, textColor=TEXT_MUTED, fontName="Helvetica-Bold", spaceAfter=4))],
        [Paragraph(clean(", ".join(matched)) or "None",
                   sty("km", fontSize=8, textColor=GREEN, leading=12)),
         Paragraph(clean(", ".join(missing)) or "None",
                   sty("kmi", fontSize=8, textColor=RED,   leading=12))],
    ]
    kw_tbl = Table(kw_data, colWidths=[(W - 36*mm) / 2] * 2)
    kw_tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), CARD),
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING",   (0, 0), (-1, -1), 7),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 7),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LINEAFTER",     (0, 0), (0, -1), 0.5, colors.HexColor("#1e293b")),
    ]))
    story.append(kw_tbl)
    story.append(Spacer(1, 3*mm))

    # ── Strengths ─────────────────────────────────────────────────────────────
    strengths = analysis.get("strengths", [])
    if strengths:
        story.append(Paragraph("💪 Strengths", S_SECTION))
        for s in strengths:
            story.append(Paragraph(f"✓  {clean(s)}", S_BULLET))
        story.append(Spacer(1, 2*mm))

    # ── Improvements ──────────────────────────────────────────────────────────
    improvements = analysis.get("improvements", [])
    if improvements:
        story.append(Paragraph("🚀 Improvement Suggestions", S_SECTION))
        for i, tip in enumerate(improvements, 1):
            story.append(Paragraph(f"<b>{i}.</b>  {clean(tip)}", S_BULLET))

    # ── Footer ────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 4*mm))
    story.append(HRFlowable(width="100%", thickness=0.5,
                            color=colors.HexColor("#1e293b")))
    story.append(Spacer(1, 2*mm))
    story.append(Paragraph(
        "Generated by <b>ATS Resume Checker</b>  ·  Powered by Google Gemini",
        sty("footer", fontSize=7, textColor=TEXT_MUTED, alignment=1, leading=9),
    ))

    # ── Build ─────────────────────────────────────────────────────────────────
    doc.build(story, onFirstPage=first_page, onLaterPages=later_page)
    return buf.getvalue()

    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    )
    from reportlab.graphics.shapes import Drawing, Circle, String, Wedge, Rect
    from reportlab.graphics import renderPDF

    # ── Colour palette ────────────────────────────────────────────────────────
    BG          = colors.HexColor("#0f0f1a")
    CARD        = colors.HexColor("#1a1f2e")
    ACCENT      = colors.HexColor("#6c63ff")
    GREEN       = colors.HexColor("#10b981")
    AMBER       = colors.HexColor("#f59e0b")
    RED         = colors.HexColor("#ef4444")
    TEXT_LIGHT  = colors.HexColor("#e2e8f0")
    TEXT_MUTED  = colors.HexColor("#94a3b8")
    WHITE       = colors.white

    W, H = A4
    buf = io.BytesIO()

    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=20*mm, rightMargin=20*mm,
        topMargin=10*mm, bottomMargin=15*mm,
    )

    styles = getSampleStyleSheet()

    def style(name, **kw):
        return ParagraphStyle(name, parent=styles["Normal"], **kw)

    S_TITLE    = style("title",    fontSize=22, textColor=WHITE,      leading=28, spaceAfter=2)
    S_SUBTITLE = style("subtitle", fontSize=11, textColor=TEXT_MUTED, leading=14, spaceAfter=6)
    S_SECTION  = style("section",  fontSize=9,  textColor=TEXT_MUTED, leading=12,
                        spaceAfter=6, spaceBefore=10,
                        fontName="Helvetica-Bold", textTransform="uppercase",
                        letterSpacing=1.2)
    S_BODY     = style("body",     fontSize=10, textColor=TEXT_LIGHT, leading=15, spaceAfter=4)
    S_BULLET   = style("bullet",   fontSize=10, textColor=TEXT_LIGHT, leading=15,
                        spaceAfter=5, leftIndent=14, firstLineIndent=-14)

    overall = analysis["overall_score"]

    def score_hex(s):
        if s >= 75: return "#10b981"
        if s >= 50: return "#f59e0b"
        return "#ef4444"

    def score_rl(s):
        return colors.HexColor(score_hex(s))

    # ── Header banner ─────────────────────────────────────────────────────────
    def header_canvas(canvas, doc):
        canvas.saveState()
        canvas.setFillColor(CARD)
        canvas.roundRect(14*mm, H - 42*mm, W - 28*mm, 34*mm, 8, fill=1, stroke=0)
        # left accent bar
        canvas.setFillColor(ACCENT)
        canvas.roundRect(14*mm, H - 42*mm, 5, 34*mm, 2, fill=1, stroke=0)
        canvas.restoreState()

    story = []

    # ── Score ring (drawn manually) ───────────────────────────────────────────
    RING_SIZE = 110
    d = Drawing(RING_SIZE, RING_SIZE)
    cx, cy, r_out, r_in = RING_SIZE/2, RING_SIZE/2, 50, 38

    # Background ring
    d.add(Circle(cx, cy, r_out, fillColor=colors.HexColor("#1e293b"), strokeColor=None))

    # Score arc: draw full wedges then overlay inner circle to create donut
    arc_degrees = overall * 3.6
    steps = max(1, int(arc_degrees / 5))
    score_col = colors.HexColor(score_hex(overall))
    for i in range(steps):
        angle_start = 90 - (i + 1) * (arc_degrees / steps)
        d.add(Wedge(cx, cy, r_out, angle_start,
                    angle_start + arc_degrees / steps + 0.5,
                    fillColor=score_col, strokeColor=None))

    # Inner cover circle creates the hollow donut effect
    d.add(Circle(cx, cy, r_in, fillColor=CARD, strokeColor=None))

    # Score text
    d.add(String(cx, cy + 6,  str(overall),
                 fontSize=22, fontName="Helvetica-Bold",
                 fillColor=score_col, textAnchor="middle"))
    d.add(String(cx, cy - 8, "/100",
                 fontSize=7, fontName="Helvetica",
                 fillColor=colors.HexColor("#64748b"), textAnchor="middle"))
    label = ("Excellent" if overall >= 85 else "Good" if overall >= 70
             else "Fair" if overall >= 50 else "Needs Work")
    d.add(String(cx, cy - 20, label,
                 fontSize=8, fontName="Helvetica-Bold",
                 fillColor=score_col, textAnchor="middle"))

    # ── Assemble header table (ring | title) ──────────────────────────────────
    title_block = [
        Paragraph("ATS Resume Analysis Report", S_TITLE),
        Paragraph(f"Role: <b>{job_role}</b>", S_SUBTITLE),
        Paragraph(f"Overall ATS Score: "
                  f"<font color='{score_hex(overall)}'><b>{overall}/100</b></font>",
                  S_BODY),
    ]
    hdr_table = Table([[d, title_block]], colWidths=[RING_SIZE + 10, None])
    hdr_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING",  (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("BACKGROUND", (0, 0), (-1, -1), CARD),
        ("ROUNDEDCORNERS", [8]),
    ]))
    story.append(hdr_table)
    story.append(Spacer(1, 6*mm))

    # ── Executive summary ─────────────────────────────────────────────────────
    summary = analysis.get("summary", "")
    if summary:
        story.append(Paragraph("Executive Summary", S_SECTION))
        story.append(Paragraph(summary, S_BODY))
        story.append(HRFlowable(width="100%", thickness=0.5,
                                color=colors.HexColor("#1e293b"), spaceAfter=4))

    # ── Section scores as bars ────────────────────────────────────────────────
    story.append(Paragraph("Section Scores", S_SECTION))

    BAR_COLORS = {
        "keywords_match":   "#6c63ff",
        "skills_alignment": "#10b981",
        "experience_match": "#f59e0b",
        "education_match":  "#3b82f6",
        "format_structure": "#ec4899",
    }
    LABELS = {
        "keywords_match":   "Keywords Match",
        "skills_alignment": "Skills Alignment",
        "experience_match": "Experience Match",
        "education_match":  "Education Match",
        "format_structure": "Format & Structure",
    }
    BAR_W = 115 * mm
    bar_rows = []
    for key, label in LABELS.items():
        sc = analysis["section_scores"].get(key, 0)
        bar_col = colors.HexColor(BAR_COLORS.get(key, "#6c63ff"))

        # Draw mini bar
        bd = Drawing(BAR_W, 14)
        bd.add(Rect(0, 4, BAR_W, 6, fillColor=colors.HexColor("#1e293b"), strokeColor=None, rx=3, ry=3))
        fill_w = BAR_W * sc / 100
        if fill_w > 0:
            bd.add(Rect(0, 4, fill_w, 6, fillColor=bar_col, strokeColor=None, rx=3, ry=3))

        label_p  = Paragraph(label, style("bl", fontSize=9, textColor=TEXT_LIGHT, leading=12))
        score_p  = Paragraph(f"<font color='{BAR_COLORS.get(key, '#6c63ff')}'><b>{sc}%</b></font>",
                             style("bp", fontSize=9, textColor=TEXT_LIGHT, leading=12))
        bar_rows.append([label_p, bd, score_p])

    bar_table = Table(bar_rows, colWidths=[50*mm, BAR_W, 15*mm])
    bar_table.setStyle(TableStyle([
        ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING",  (0, 0), (-1, -1), 3),
        ("RIGHTPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
        ("TOPPADDING",   (0, 0), (-1, -1), 2),
    ]))
    story.append(bar_table)
    story.append(Spacer(1, 4*mm))

    # ── Keywords ──────────────────────────────────────────────────────────────
    matched = analysis.get("matched_keywords", [])
    missing = analysis.get("missing_keywords", [])

    kw_data = [
        [Paragraph(f"✅ Matched Keywords ({len(matched)})", S_SECTION),
         Paragraph(f"❌ Missing Keywords ({len(missing)})", S_SECTION)],
        [Paragraph(", ".join(matched) or "None",
                   style("m", fontSize=9, textColor=GREEN, leading=13)),
         Paragraph(", ".join(missing) or "None",
                   style("mi", fontSize=9, textColor=RED, leading=13))],
    ]
    kw_table = Table(kw_data, colWidths=[(W - 40*mm) / 2] * 2)
    kw_table.setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (-1, -1), CARD),
        ("VALIGN",       (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING",  (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING",   (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 8),
        ("GRID",         (0, 0), (-1, -1), 0.5, colors.HexColor("#1e293b")),
        ("ROUNDEDCORNERS", [6]),
    ]))
    story.append(kw_table)
    story.append(Spacer(1, 4*mm))

    # ── Strengths ─────────────────────────────────────────────────────────────
    strengths = analysis.get("strengths", [])
    if strengths:
        story.append(Paragraph("💪 Strengths", S_SECTION))
        for s in strengths:
            story.append(Paragraph(f"✓  {s}", S_BULLET))
        story.append(Spacer(1, 3*mm))

    # ── Improvements ──────────────────────────────────────────────────────────
    improvements = analysis.get("improvements", [])
    if improvements:
        story.append(Paragraph("🚀 Improvement Suggestions", S_SECTION))
        for i, tip in enumerate(improvements, 1):
            story.append(Paragraph(f"<b>{i}.</b>  {tip}", S_BULLET))

    # ── Footer ────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 6*mm))
    story.append(HRFlowable(width="100%", thickness=0.5,
                            color=colors.HexColor("#1e293b")))
    story.append(Spacer(1, 2*mm))
    story.append(Paragraph(
        "Generated by <b>ATS Resume Checker</b> · Powered by Google Gemini",
        style("footer", fontSize=8, textColor=TEXT_MUTED,
              alignment=1, leading=10)
    ))

    # ── Build ─────────────────────────────────────────────────────────────────
    doc.build(story, onFirstPage=header_canvas, onLaterPages=header_canvas)
    return buf.getvalue()
